version: "3.8"

services:
  squid:
    build:
      context: ./squid
    container_name: squid_proxy
    restart: always
    ports:
      - "3128:3128"
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
    networks:
      - proxy_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3128 || exit 1"]
      interval: 20s
      retries: 3

  haproxy:
    image: haproxy:latest
    container_name: haproxy_lb
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - proxy_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 20s
      retries: 3

  api:
    build:
      context: ./api
    container_name: proxy_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      # Sets the environment to production. Possible values: development, production, testing
      - FLASK_ENV=production
    networks:
      - proxy_network

  monitoring:
    build:
      context: ./monitoring
    container_name: monitoring_service
    restart: always
    ports:
      - "6000:6000"
    networks:
      - proxy_network

  web-dashboard:
    image: nginx:latest
    container_name: web_dashboard
    restart: always
    ports:
      - "8081:80"
      - ./web_dashboard:/usr/share/nginx/html
      - ./web-dashboard:/usr/share/nginx/html
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge
